@endpoint = https://ntpkcrvuhf.execute-api.us-east-1.amazonaws.com/prod
GET {{endpoint}}/hello
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "London",
    "name": "Best Location"
}
###